# Generated by Django 3.1 on 2020-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminspost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='friends')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
